### ISSUE TITLE
API Key should be token

### ISSUE THREAD

**Issue by timeisenhauer** [chrisnicola/Mixpanel.NET#10]
var tracker = new Tracker("your API key");

Note that "your API key" should actually by your Mixpanel project token.

**Comment by chrisnicola** [comment]
Thanks @timeisenhauer. I'd love to update this but I'm mostly doing non .NET stuff. I've been thinking of making this mono capable and developing it from *nix. If you submit a pull request though I'll accept it.

**Comment by chrisnicola** [comment]
BTW is everything still working?

**Comment by timeisenhauer** [comment]
Everything seems good so far ... though I've only just scraped the surface with trackers.  Thanks!
